# 使用语言
language: node_js
# node版本
node_js: stable
# 设置只监听哪个分支
branches:
  only:
  - master
# 缓存，可以节省集成的时间，这里我用了yarn，如果不用可以删除
cache:
  apt: true
  npm: true
  directories:
    - node_modules
# tarvis生命周期执行顺序详见官网文档
before_install:
- git config --global user.name "ferry"
- git config --global user.email "ferryvip@163.com"
- npm install -g hexo-cli gh-pages
install:
- npm i
script:
- hexo clean
- hexo generate
after_success:
- gh-pages -d public -b master -r $GSOURCE

- cd ./public
- git init
- git add --all .
- git commit -m "Travis CI Auto Builder"

- git push --quiet --force $GITHUB gh-pages

# 这里的 REPO_TOKEN 即之前在 travis 项目的环境变量里添加的

- git push --quiet --force $CODING coding-pages